spring.application.name=devnav

spring.datasource.url=jdbc:postgresql://localhost:5432/devnav_handbook
spring.datasource.username=muraokakanemichi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true